POST http://localhost:2000/api/auth/register
Content-Type: application/json

{
    "username": "john",
    "email": "john@doe.com",
    "password": "00000000"
}

###
POST http://localhost:2000/api/auth/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "000000000"
}

###
POST http://localhost:2000/api/auth/forgotpassword

###
PUT http://localhost:2000/api/auth/resetpassword/1999

###

