POST http://localhost:2000/api/auth/register
Content-Type: application/json

{
    "username": "kyaw",
    "email": "kyawlinnaingwin9@gmail.com",
    "password": "00000000"
}

###
POST http://localhost:2000/api/auth/login
Content-Type: application/json

{
    "email": "kyawlinnaingwin9@gmail.com",
    "password": "00000000"
}

###
POST http://localhost:2000/api/auth/forgotpassword
Content-Type: application/json

{
    "email": "kyawlinnaingwin9@gmail.com"
}

###
PUT http://localhost:2000/api/auth/resetpassword/26eebf0527f08eafd6d2e3c6963cd1a1300c0876
Content-Type: application/json

{
    "password": "00000000"
}

###

GET http://localhost:2000/api/private/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2Q3NjI1MTgxMjM3OGM4M2UxZTNmMiIsImlhdCI6MTY0ODIwMjQ4MCwiZXhwIjoxNjQ4MjAyNzgwfQ.I-TlT3OMj4C1JM9P3rOtagaN1tvvCGDiBsn07igZC9M

###

